### ISSUE TITLE
Update Apache commons-io to 2.2. or higher

### ISSUE THREAD

**Issue by mwunderlich** [dkpro/dkpro-tc#265]
The version currently used (2.0.1.) is five years old. 

Once the lib is updated, FileUtils should be used in ContextCollectorUFE.writeOutput() to avoid getting a literal "\t" instead of a tab character in the output file.

**Comment by reckart** [comment]
I'd say feel free to update, how about version 2.4? I'll also make the upgrade in Core (unless it breaks something).

**Comment by mwunderlich** [comment]
2.4 sounds good. :)

**Comment by mwunderlich** [comment]
I had a look where the version for commons-io is derived from (its a managed dependency) and I found it in DKpro Core: dkpro-core/de.tudarmstadt.ukp.dkpro.core-asl/pom-xml
So, as soon as you have made the change there, it should trickle down to the other projects and modules.

**Comment by reckart** [comment]
The change in Core is already done: https://github.com/dkpro/dkpro-core/commit/fa30944c24bdce1915a1e481f6817fe6ed0b46c8

**Comment by mwunderlich** [comment]
Ah, ok. Sorry, I should have checked.

**Comment by mwunderlich** [comment]
Just one more thing. Dkpro TC is currently using the release version of Dkpro Core (1.7.0). In order to make this update available, we'd have to use 1.8.0-SNAPSHOT instead. 
Is there anything that would speak against using the Snapshot version?

**Comment by zesch** [comment]
It is a matter of release cycles.
Once we have the Core snapshot in TC, a TC release is bound to a Core
release.
Given the periodically rapid development of TC, this might cause problems.

@Richard: Is there already a release plan for the next Core version?

-Torsten

2015-08-27 12:06 GMT+02:00 Martin Wunderlich notifications@github.com:

**Comment by reckart** [comment]
There is no release plan for DKPro Core 1.8.0 yet. We have sufficient changes to make a release, but nobody stepped up so far to drive the release. Also, the release guide probably needs quite some updating after the move to Github - and various decisions need to be made regarding what to drop fro 1.8.0 because it is not ready/mature/etc. But this is not the right venue to discuss details.

**Comment by daxenberger** [comment]
I would not want to be dependent on the Core 1.8.0 release for the next TC release. Unless this is a blocker, I'd like to wait with the upgrade to Core 1.8.0-SNAPSHOT. AFAIK, Core 1.8.0 also requires Java 8 which TC currently does not support.

**Comment by reckart** [comment]
Yep. Core is on Java 8. Likewise DKPro Lab 0.12.0-SNAPSHOT since yesterday (and yes, I already started using Java 8 features).
But just for upgrading a few dependencies, it isn't necessary to wait for a new DKPro Core release (I wouldn't agree with renaming the issue rather with opening another one). Just add managed dependencies for those libraries you want to upgrade to the TC pom. This works fine as long as the new versions are backwards compatible (and Apache Commons are very good in that respect).

**Comment by daxenberger** [comment]
Agree. That makes two new issues: Upgrade to Java 8 and upgrade to Core 1.8.0 (once it's released).

**Comment by mwunderlich** [comment]
Hi Johannes, 

Are there any known issues with Java 1.8 in TC? 

Cheers, 

Martin

**Comment by daxenberger** [comment]
No, not yet ;-)
Maybe some of the internal libraries we're using, but I don't think that's too much work.

**Comment by reckart** [comment]
Java 8 is a bit more picky about correct Javadoc formatting ;)

**Comment by daxenberger** [comment]
Jepp; that might be most work-intense part ...
