### ISSUE TITLE
CRFSuite binary: Windows 64 bit binary is missing

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#305]
The 64bit binary of CRFSuite for Windows systems is missing. At the moment we only have the 32-bit binary.
It should be possible to just copy it and use it as 64bit binary, but it would be better to have a real 64bit binary.

**Comment by reckart** [comment]
Cf. https://github.com/dkpro/dkpro-core/issues/318

**Comment by Horsmann** [comment]
I updated the installation script and copy the file during installation.
@reckart Could you add the new version into artifactory?

**Comment by reckart** [comment]
@Horsmann the binary artifact should have its version increased - I guess to from "20140918.0" to "20140918.1" - and the dependencies in the POM need to be upgraded correspondingly. Otherwise, Maven will not download the new JAR with the additional binary.

@betoboullosa could you deploy the new crfsuite artifact please once the version stuff is fixed?

**Comment by Horsmann** [comment]
fixed

**Comment by betoboullosa** [comment]
OK, new artifacts deployed to zoidberg. Closing the issue.

**Comment by reckart** [comment]
@Horsmann have you ever had the chance of testing whether the crfsuite binary actually works on Windows 64bit?

**Comment by reckart** [comment]
Never mind. Found out that I had to install the **Microsoft Visual C++ 2010 SP1 Redistributable Package** (32bit version) for the crfsuite binary to work.
