### ISSUE TITLE
TestCases fail on Windows-Jenkins

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-tc#451]

**Comment by Horsmann** [comment]
@reckart Is there a way to see the build-folders of the Windows-JEnkins? I can't really track why it is not able to find the file it is looking for. On my Windows VM this works now but WinJenk keeps failing at this particular test case. This is hard to diagnose from here :/

**Comment by reckart** [comment]
Hm... not so easy. What are you looking for?

**Comment by Horsmann** [comment]
I think I might have found it. Thanks anyway :)

**Comment by Horsmann** [comment]
@reckart Can you dig-out from Win-jenkins the full stack-trace of this test-failure? https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/DKPro%20Text%20Classification%20Framework%20(GitHub)%20-%20Windows/121/org.dkpro.tc$dkpro-tc-examples-groovy/testReport/org.dkpro.tc.groovyexamples.single.sequence/BrownPosDemoTest/testGroovyCrossValidation/

I can't really see what is the problem with this Groovy test :/

**Comment by Horsmann** [comment]
@reckart Do you have any idea why a test case would fail if executed as Groovy script? I have no problems when executing via Java directly.

**Comment by reckart** [comment]
My guess would be that the problem may be related to line endings since it only occurs on Windows and from the error message seems to be related to seeking in a string (I might be wrong - did only look at the error message, not at the code).

It works on Java but not on Groovy...? No idea. Is some data written/read in slightly different ways between the Java and Groovy version?

**Comment by Horsmann** [comment]
@reckart I made some progress with this one. It seems that some Windows do not necessarily come with the required `C Runtime Libary`. I set up a Windows 10 VM, since I could not produce this error with my Windows 7 VM. I managed to reproduce a similarly looking error. (I still have no answer why the Java-Tests pass and only the one Groovy test fails but this a least a possibility that is inexpensively to test - with your help...).

The problems solution to my VM-based investigation was installing `Visual C++ 2010 Redistributional`, which comes with the required DLLs. @reckart, `could you install them on the Windows Jenkins?`, I would like to give it a try if this might be the cause for the error. You don't see the DLL error message unless you try to manually execute the crfsuite binary from command line. All you see in the TC-StackTrace is a missing file exception. The package with the DLLs can be downloaded here: https://www.microsoft.com/de-de/download/details.aspx?id=5555, it is a only a small update to  install.

**Comment by reckart** [comment]
I am pretty sure that these are already installed on the Jenkins slave - I even documented that in the DKPro Core user setup section for Windows: https://dkpro.github.io/dkpro-core/releases/1.9.0/docs/user-guide.html#_windows

**Comment by reckart** [comment]
So what I can see in the logs of Jenkins for the failing test is this:

```
CRFSuite 0.12  Copyright (c) 2007-2011 Naoaki Okazaki
Start time of the training: 2018-02-21T18:54:20Z
Reading the data set(s)
ERROR: Failed to open the data set: E:\svc_jenkins\workspace\DKPro Text Classification Framework (GitHub) - Windows\dkpro-tc-examples-groovy\target\repository\ReutersDemoTest\testGroovyTrainTest\org.dkpro.lab\repository\ExtractFeaturesTask-Train-BrownPosDemo-TrainTest-Groovy-20180221195415128\output\featureFile.txt
```

The problem here is most likely that `E:\svc_jenkins\workspace\DKPro Text Classification Framework (GitHub) - Windows\dkpro-tc-examples-groovy\target\repository\ReutersDemoTest\testGroovyTrainTest\org.dkpro.lab\repository\ExtractFeaturesTask-Train-BrownPosDemo-TrainTest-Groovy-20180221195415128\output\featureFile.txt` is a path of 280 characters - which is too long for Windows (cf. e.g. https://stackoverflow.com/questions/1065993/has-windows-7-fixed-the-255-character-file-path-limit or search on the web).

A solution might be to pass a relative path to CRFSuite instead of an absolute path.

**Comment by Horsmann** [comment]
Thanks!. 

I added a work-around that tests for windows+long paths and then copies everything into the directory of the binary. This is a bit slower because data is copied but this works at least also on Windows.

**Comment by reckart** [comment]
if you can move instead of copy, it could be faster

**Comment by Horsmann** [comment]
True, I thought about it but if something goes wrong it might add to the confusions why the training/testing data are not where they are supposed to be. I rather go whith copying for this case. Furthermore, I would expect that this is more an issue for Jenkins environments. I don't expect that deep file-hierarchies for normal use cases.
