### ISSUE TITLE
Feature extractors returning more than one feature with same name cause IndexOutOfBoundsException

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-tc#95]
Originally reported on Google Code with ID 95

```
This might not be the expected behaviour. We should check for this early and throw a
better exception. One location to do so, is the Instance class. We might also re-implement
the Feature class (is a TODO anyways) to specify that features are equal when they
have the same name. That would make it easier, to check for Feature Extractors returning
faulty feature lists.
Opinions?

```

Reported by `daxenberger.j` on 2014-02-21 08:57:35

**Comment by Horsmann** [comment]
Bug fixes introduced a N-times higher memory demand

**Comment by Horsmann** [comment]
What is left to do:
A feature extractor might still return the same feature twice and an instance thus might have the same feature two or more times (if the user does not pay attention).

Attempts to solve this:
- Keep a namelist in the Instance.java to track if the same name has been added before
- Using TreeSets instead of a List to store the features

Issues:
- Keeping track of the names in the Instance class takes quite some RAM. This becomes a serious memory issue for large training sets for instance the full Wall-Street-Journal.
- The feature stores (Dense and Sparse) keep track of the names too. Double-tracking in the Instance class or using TreeSets (also quite memory demanding) wastes a lot of info for storing information which is already in memory (although unreachable from the Instance class atm).
- Dirty hacks will probably work for small to mid-sized datasets, but large training data will demand an unreasonable amount of RAM.

Conclusion:
The remaining task should be tackled together with a redesign of the feature stores. The names have to be kept in memory anyway - with some redesign this should be possible without having to store everything twice (hopefully)

**Comment by reckart** [comment]
How many unique feature names do you typically have?

**Comment by Horsmann** [comment]
836 at the moment. By using a Set to store all names in each Instance, an instance would have to store all 836 names. The WSJ has around 1.100.000 tokens, this easily adds up.

**Comment by reckart** [comment]
Sure ;) If you create new instances of the names every time, you'll clogg your memory. When you create a new feature name, use `intern()` to get a unique instance. In that way you make sure that for every unique String you only have a single instance in memory:

```
String featureName = constructFeatureName().intern();
```

**Comment by zesch** [comment]
> What is left to do:
> A feature extractor might still return the same feature twice and an instance thus might have the same > feature two or more times (if the user does not pay attention).

This is actually not possible, as all FEs now have Set<Feature> as return type.

Regarding the feature stores: There is certainly endless potential to optimize them further :)

**Comment by reckart** [comment]
> > What is left to do:
> > A feature extractor might still return the same feature twice and an instance thus might have the same >> feature two or more times (if the user does not pay attention).
> 
> This is actually not possible, as all FEs now have Set as return type.
> 
> Regarding the feature stores: There is certainly endless potential to optimize them further :)

Are you sure? The equals/hashCode/compareTo functions of Feature do not only take the name into account but also the value. Unless you use a set with a custom comparator, the same feature could still be added as along as it has a different value.

**Comment by zesch** [comment]
This is a bug then. It should only depend on the name.
